import { KlipperConfigHelper } from '../helpers/klipper-config';
import { PrinterConfiguration } from '../zods/printer-configuration';

export const template = (config: PrinterConfiguration, helper: KlipperConfigHelper) => `
# WARNING. THIS FILE IS GENERATED BY THE RATOS CONFIGURATOR.
# CHANGES YOU MAKE HERE WILL BE OVERWRITTEN. KEEP YOUR CHANGES IN PRINTER.CFG.
# Rat Rig V-Minion Klipper Config
# Documentation: https://os.ratrig.com

#############################################################################################################
### CONTROLBOARD & TOOLBOARD
#############################################################################################################
${helper.renderBoardIncludes()}

#############################################################################################################
### BASE SETUP
#############################################################################################################
[include RatOS/printers/voron-v24/voron-v24.cfg]
[include RatOS/homing.cfg]
[include RatOS/macros.cfg]
[include RatOS/shell-macros.cfg]
[include RatOS/printers/voron-v24/macros.cfg]

# Extruder
${helper.renderExtruder()}

# Hotend
${helper.renderHotend()}

# ADXL345 resonance testing configuration
${helper.renderInputShaper(180)}

#############################################################################################################
### STEPPER MOTORS, DRIVERS & SPEED LIMITS
### Pick the drivers and stepper motors you're using. See the RatOS documentation for custom combinations.
#############################################################################################################
[include RatOS/printers/voron-v24/steppers.cfg]

# UNCOOLED TMC 2209 + LDO-42STH48-2004MAH on XY + LDO-42STH48-2004AC on Z
${helper.uncommentIf(!config.performanceMode)}[include RatOS/printers/voron-v24/tmc2209.cfg]
${helper.uncommentIf(!config.performanceMode)}[include RatOS/printers/voron-v24/speed-limits-basic.cfg]
${helper.uncommentIf(!config.performanceMode)}[include RatOS/steppers/ldo/42sth48-2004mah/2209/24v-0.8a-x.cfg]
${helper.uncommentIf(!config.performanceMode)}[include RatOS/steppers/ldo/42sth48-2004mah/2209/24v-0.8a-y.cfg]
${helper.uncommentIf(!config.performanceMode)}[include RatOS/steppers/ldo/42sth48-2004ac/2209/24v-0.8a-z.cfg]
${helper.uncommentIf(!config.performanceMode)}[include RatOS/steppers/ldo/42sth48-2004ac/2209/24v-0.8a-z1.cfg]
${helper.uncommentIf(!config.performanceMode)}[include RatOS/steppers/ldo/42sth48-2004ac/2209/24v-0.8a-z2.cfg]
${helper.uncommentIf(!config.performanceMode)}[include RatOS/steppers/ldo/42sth48-2004ac/2209/24v-0.8a-z3.cfg]

# UNCOOLED TMC 2209 + LDO-42STH48-2504AC on XYZ

# PERFORMANCE MODE: COOLED TMC 2209 + LDO-42STH40-1684AC
${helper.uncommentIf(config.performanceMode)}[include RatOS/printers/v-minion/tmc2209.cfg]
${helper.uncommentIf(config.performanceMode)}[include RatOS/printers/v-minion/speed-limits-performance.cfg]
${helper.uncommentIf(config.performanceMode)}[include RatOS/steppers/ldo/42sth40-1684ac/2209/24v-1.188a-x.cfg]
${helper.uncommentIf(config.performanceMode)}[include RatOS/steppers/ldo/42sth40-1684ac/2209/24v-1.188a-y.cfg]
${helper.uncommentIf(config.performanceMode)}[include RatOS/steppers/ldo/42sth40-1684ac/2209/24v-1.188a-z.cfg]

# STEALTH MODE
${helper.uncommentIf(config.stealthchop)}[include RatOS/printers/v-minion/speed-limits-stealth.cfg]
${helper.uncommentIf(config.stealthchop)}[include RatOS/printers/v-minion/tmc2209-stealth.cfg]

${helper.renderDriverOverrides()}

${helper.renderStepperOverrides()}

#############################################################################################################
### HOMING
### Pick your probe and endstops
#############################################################################################################
${helper.renderProbeIncludes()}

${helper.renderEndstopSection()}


#############################################################################################################
### FANS
### If your board has 4 pin fan headers and you want to use them, you can enable them here.
### NOTE: If none are uncommented, the default 2pin fan headers will be used.
#############################################################################################################
# Part cooling
${helper.uncommentIf(config.partFan.id === '4pin-dedicated')}[include RatOS/4pin-fans/part-cooling-fan-25khz.cfg]

# Hotend / Toolhead cooling
${helper.uncommentIf(config.hotendFan.id === '4pin-dedicated')}[include RatOS/4pin-fans/toolhead-fan-25khz.cfg]

# Control board cooling
${helper.uncommentIf(config.controllerFan.id === '4pin-dedicated')}[include RatOS/4pin-fans/controller-fan-25khz.cfg]

${helper.renderFanOverrides()}
`;

export const initialPrinterCfg = (config: PrinterConfiguration, helper: KlipperConfigHelper) => `
#############################################################################################################
### CONFIGURATION GENERATED BY THE RATOS CONFIGURATOR
#############################################################################################################
[include RatOS.cfg]

#############################################################################################################
### MACRO CONFIGURATION
### Configure the behavior of RatOS macros
### See: https://os.ratrig.com/docs/configuration/macros
#############################################################################################################
[gcode_macro RatOS]
variable_relative_extrusion: False
variable_preheat_extruder: True
variable_calibrate_bed_mesh: True
variable_nozzle_priming: "primeblob"
variable_start_print_park_in: "front"
variable_start_print_park_z_height: 50
variable_end_print_park_in: "back"
variable_pause_print_park_in: "front"
variable_macro_travel_speed: 300

#############################################################################################################
### USER OVERRIDES & CUSTOM CONFIGURATION
### Anything custom you want to add, or RatOS configuration you want to override, do it here.
### This section is pre-populated with the most common settings you may want to change.
### See: https://os.ratrig.com/docs/configuration/includes-and-overrides
###
### It is recommended that you follow these steps to properly calibrate your printer:
### 0) Sanity check and PID Tuning: https://www.klipper3d.org/Config_checks.html
### 1) Pressure Advance: https://www.klipper3d.org/Pressure_Advance.html
### 2) Skew Correction: https://www.klipper3d.org/Skew_Correction.html
### 3) Resonance Compensation: https://www.klipper3d.org/Resonance_Compensation.html
### RatOS has dedicated macro's to generate shaper graphs for deeper analysis (requires accelerometer).
### Use MEASURE_COREXY_BELT_TENSION to compare tension between belts, and use
### GENERATE_SHAPER_GRAPHS to generate the resonance graphs for analysing and manually entering input shaper
### configuration.
### You can run SHAPER_CALIBRATE to automatically calibrate your input shaper configuration, if you just want
### to get started.
### Read more about klipper here: https://www.klipper3d.org/Overview.html
#############################################################################################################

[stepper_x]
dir_pin: !x_dir_pin # Add ! in front of pin name to reverse X stepper direction
rotation_distance: 40 # 40 for 20 tooth 2GT pulleys, 32 for 16 tooth 2GT pulleys
position_endstop: 0 # Adjust this to your setup
position_min: 0 # Adjust this to your setup
position_max: 180 # Adjust this to your setup

[stepper_y]
dir_pin: y_dir_pin # Add ! in front of pin name to reverse Y stepper direction
rotation_distance: 40 # 40 for 20 tooth 2GT pulleys, 32 for 16 tooth 2GT pulleys
position_endstop: 0 # Adjust this to your setup
position_min: 0 # Adjust this to your setup
position_max: 180 # Adjust this to your setup

[stepper_z]
dir_pin: !z0_dir_pin # Add ! in front of pin name to reverse Z stepper direction
rotation_distance: 4 # 4 for TR8*4 lead screws

# Pressure Advance
# Check https://www.klipper3d.org/Pressure_Advance.html for pressure advance tuning.
[extruder]
# pressure_advance: 0.05
dir_pin: !${helper.getExtruderPinPrefix()}e_dir_pin # Remove ! in front of pin name to reverse extruder direction
nozzle_diameter: 0.4 # Remember to change this if you change nozzle diameter.
control: pid
pid_kp: 21.673
pid_ki: 1.338
pid_kd: 87.776

[heater_bed]
control: pid
pid_kp: 68.203
pid_ki: 2.842
pid_kd: 409.216

${helper.renderProbePinSection()}
`;
