import { serverSchema } from '@/env/schema.mjs';
import { replaceOrAddIniSectionsFromFileSync } from '@/server/helpers/file-operations';
import { getLogger } from '@/server/helpers/logger';
import { GetRequiredPinAliasesFn, RenderTemplateFn } from '@/templates/template-api';
import { existsSync, readFileSync } from 'fs';
import path from 'path';

export const getRequiredPinAliases: GetRequiredPinAliasesFn = (ctx) => {
	return ['ratrig_vaoc_probe_pin', 'ratrig_vaoc_led_pin', 'ratrig_vaoc_fan_pin'];
};

export const renderTemplate: RenderTemplateFn = (ctx) => {
	switch (ctx.section) {
		case 'hardware':
			const updatedCrowsnestContent = getUpdatedCrowsnestConfigurationForVaoc();
			ctx.extrasGenerator.addFileToRender({
				fileName: 'crowsnest.conf',
				content: updatedCrowsnestContent,
				overwrite: true,
			});
			return `
###########################
# RatRig VAOC configuration
###########################

# The [cam 1] section in crowsnest.conf must be replaced with the following
# (with the # characters removed) to enable the VAOC camera:

#[cam 1]
#mode: camera-streamer
#enable_rtsp: false
#rtsp_port: 8554
#port: 8080
#device: /dev/video0
#resolution: 1920x1080
#max_fps: 30

[z_offset_probe]
pin: ^${ctx.getPrefixedPinFromAlias('ratrig_vaoc_probe_pin')}  # probe trigger pin
z_offset: -7                 # probe height, used to limit the probe z-move
y_offset: 0                  # probe y-offset, measured from the camera centre
x_offset: 37.5               # probe x-offset, measured from the camera centre
speed: 10                    # probe speed  
samples: 3                   # number of samples  
sample_retract_dist: 5
lift_speed: 10.0
samples_result: median
samples_tolerance: 0.2
samples_tolerance_retries: 5

[neopixel vaoc_led]
pin: ${ctx.getPrefixedPinFromAlias('ratrig_vaoc_led_pin')}
chain_count: 6
color_order: GRB

[heater_fan vaoc_fan]
pin: ${ctx.getPrefixedPinFromAlias('ratrig_vaoc_fan_pin')}
heater: heater_bed
fan_speed: 1.0
heater_temp: 50
`;
		case 'config-helpers':
			// If overwrite is requested (or overwrite details are not available), reset dc-endstop.cfg.
			// Otherwise, use the existing content or the default content if the file does not exist.
			const dcEndstopCfgFileName = 'ratos_generated/dc-endstop.cfg';
			const dcEndstopContent = getDcEndstopConfigurationFileContent(dcEndstopCfgFileName);
			ctx.extrasGenerator.addFileToRender({
				fileName: dcEndstopCfgFileName,
				content: dcEndstopContent,
				overwrite: true,
			});

			// Ditto, for adjust-y-max.cfg.
			const adjustYMaxCfgFileName = 'ratos_generated/adjust-y-max.cfg';
			const adjustYMaxContent = getAdjustYMaxConfigurationFileContent(adjustYMaxCfgFileName);
			ctx.extrasGenerator.addFileToRender({
				fileName: adjustYMaxCfgFileName,
				content: adjustYMaxContent,
				overwrite: true,
			});

			return `
########################################
# Configuration Helpers for Rat Rig VAOC
########################################
#
# These includes must come after any user-defined stepper sections
# to ensure that overrides work correctly.
#
[include ratos_generated/dc-endstop.cfg]   # Managed by CONFIGURE_DC_ENDSTOP macro
[include ratos_generated/adjust-y-max.cfg] # Managed by INCREASE_Y_MAX macro
`;
		default:
			throw new Error(`Unknown purpose '${ctx.section}' for template rendering.`);
	}
};

export function getUpdatedCrowsnestConfigurationForVaoc() {
	const environment = serverSchema.parse(process.env);
	const crowsnestPath = path.join(environment.KLIPPER_CONFIG_PATH, 'crowsnest.conf');
	return replaceOrAddIniSectionsFromFileSync(crowsnestPath, [
		{
			section: 'cam 1',
			body: `# Required for Rat Rig VAOC camera integration, DO NOT MODIFY THIS SECTION.
mode: camera-streamer
enable_rtsp: false
rtsp_port: 8554
port: 8080
device: /dev/RatOS/rr-vaoc-camera
resolution: 1920x1080
max_fps: 30
`.trim(),
		},
	]);
}

function getCommonBoilerplateConfigurationFileContent(fileName: string, macroName: string): string {
	const environment = serverSchema.parse(process.env);
	const configPath = path.join(environment.KLIPPER_CONFIG_PATH, fileName);
	const exists = existsSync(configPath);
	getLogger().debug(`getting content for ${fileName}, exists=${exists}`);
	if (!exists) {
		return `# WARNING. THIS FILE IS GENERATED BY RATOS AND
# WILL BE UPDATED BY THE ${macroName} MACRO.
# DO NOT DELETE OR MODIFY THIS FILE.
`;
	}
	return readFileSync(configPath, 'utf-8');
}

function getDcEndstopConfigurationFileContent(fileName: string): string {
	return getCommonBoilerplateConfigurationFileContent(fileName, 'CONFIGURE_DC_ENDSTOP');
}

function getAdjustYMaxConfigurationFileContent(fileName: string): string {
	return getCommonBoilerplateConfigurationFileContent(fileName, 'INCREASE_Y_MAX');
}
