[server]
host: 0.0.0.0
port: 7125
max_upload_size: 16384
klippy_uds_address: ~/printer_data/comms/klippy.sock

[announcements]
subscriptions:
  RatOS
  mainsail

[file_manager]
enable_object_processing: False

[update_manager]
refresh_interval: 168
enable_auto_refresh: True

[update_manager RatOSTheme]
type: git_repo
path: ~/printer_data/config/.theme
origin: https://github.com/Rat-OS/RatOS-theme.git
is_system_service: False
primary_branch: v2.1.x
info_tags:
	desc=RatOS Core: Theme

[update_manager ratos-configurator]
type: git_repo
path: ~/ratos-configurator
primary_branch: v2.1.x-deployment-2
origin: https://github.com/Rat-OS/RatOS-configurator.git
install_script: configuration/scripts/ratos-common.sh
virtualenv: ~/klippy-env
requirements: configuration/klippy/requirements.txt
is_system_service: True
managed_services:
	ratos-configurator
	moonraker
	klipper
info_tags:
	desc=RatOS Core: Configurator & Configuration

[update_manager mainsail]
type: web
channel: stable
repo: mainsail-crew/mainsail
path: ~/mainsail
info_tags:
	desc=External: Mainsail Web Interface

[update_manager crowsnest]
type: git_repo
path: ~/crowsnest
origin: https://github.com/mainsail-crew/crowsnest.git
install_script: tools/pkglist.sh
managed_services: crowsnest
info_tags:
	desc=External: Crowsnest Webcam Manager

[update_manager timelapse]
type: git_repo
primary_branch: main
path: ~/moonraker-timelapse
origin: https://github.com/mainsail-crew/moonraker-timelapse.git
managed_services: klipper moonraker
info_tags:
	desc=External: Timelapse Moonraker Plugin

[update_manager LinearMovementAnalysis]
type: git_repo
path: ~/klipper_linear_movement_analysis
primary_branch: main
origin: https://github.com/worksasintended/klipper_linear_movement_analysis.git
install_script: install.sh
virtualenv: ~/klippy-env
requirements: requirements.txt
is_system_service: False
managed_services: 
	klipper
info_tags:
	desc=External: Linear Movement Analysis

[update_manager KlipperScreen]
type: git_repo
path: ~/KlipperScreen
origin: https://github.com/KlipperScreen/KlipperScreen.git
virtualenv: ~/.KlipperScreen-env
requirements: scripts/KlipperScreen-requirements.txt
system_dependencies: scripts/system-dependencies.json
managed_services: KlipperScreen
pinned_commit: 71eef9ee1f23aa4fd6b68169cfe5dd7908e478b2
info_tags:
	desc=External: KlipperScreen Touchscreen Interface

[update_manager beacon]
type: git_repo
channel: dev
path: ~/beacon
origin: https://github.com/beacon3d/beacon_klipper.git
virtualenv: ~/klippy-env
requirements: requirements.txt
install_script: install.sh
is_system_service: False
managed_services: klipper
info_tags:
	desc=External: Beacon Surface Scanner

# enables moonraker to track and store print history.
[history]

# enables partial support of Octoprint API
[octoprint_compat]

[update_manager klipper]
channel: dev
pinned_commit: 2817b348e23c779b68ae5f27f2b9b9af8cfcf0da

[update_manager moonraker]
channel: dev
pinned_commit: 71f9e677b81afcc6b99dd5002f595025c38edc7b
